var setting = ["EPIC", "END TIMES-THEMED", "OCCULT-THEMED", "ARTISTIC", "OPEN WORLD", "APOCALYPTIC", "OLD-TIMEY", "ZOMBIE-THEMED", "PARALLEL UNIVERSE-THEMED", "FANTASY", "SCI-FI", "DYSTOPIAN", "SURREALIST", "WHIMSICAL", "HUMOROUS", "ROMANTIC", "DRAMATIC", "SUPERNATURAL", "LEGENDARY", "FOLK-LORE DRIVEN", "PHILOSOPHICAL", "POLITICAL", "SATIRICAL", "CYBERPUNK", "RETRO", "NON-LINEAR", "RELIGIOUS", "ZEN-LIKE", "PIRATE-THEMED", "TIME-TRAVEL THEMED", "NATURAL DISASTER-THEMED", "HARDCORE", "ROBOT INVASION-THEMED", "CRIME & MYSTERY-THEMED", "HACKING-THEMED", "MYTHOLOGICAL", "VICTORIAN-ERA", "POST-APOCALYPTIC", "PSYCHEDELIC" ];

var genre = ["ACTION-ADVENTURE", "SIDE-SCROLLER", "PLATFOFMER", "SHOOT-EM UP", "SURVIVAL HORROR", "HORROR", "TURN-BASED RPG", "TURN-BASED STRATEGY GAME", "RPG", "STEALTH GAME", "METROIDVANIA", "SIMULATION GAME", "TOWER DEFENSE", "WARGAME", "PUZZLER", "IDLE GAME", "INCREMENTAL GAME", "NON-GAME", "HACK-AND-SLASH", "BATTLE ARENA", "DUNGEON CRAWLER", "ACTION RPG", "ISOMETRIC RPG", "CITY-BUILDER", "WAVE-BASED GAME", "ROGUELITE", "ROGUELIKE", "RACING GAME", "PARTY GAME", "ROUND-BASED TACTICS GAME", "CONSERVATION GAME", "RESOURCE-MANAGEMENT GAME", "SPORTS GAME", "GRAND STRATEGY", "TEXT ADVENTURE", "VISUAL NOVEL", "TYCOON GAME", "CARD GAME", "VOXEL GAME", "STORY-DRIVEN GAME", "REAL-TIME STRATEGY GAME", "BEAT-EM UP", "POINT-AND-CLICK ADVENTURE", "FIRST-PERSON SHOOTER", "THIRD-PERSON SHOOTER" ];

var verb = ["FORMULATE A PLAN", "COLLECT POWER-UPS", "MAKE UNCONVINCING EXCUSES", "BREAK THE 4TH WALL", "MAKE HISTORY", "GO ON A SOLO EXPEDITION", "EXPERIENCE TRAGEDY", "DEAL WITH PAST-EXPERIENCES", "START WITH NOTHING", "COMMIT A CRIME PUNISHABLE BY DEATH", "ARE ENSLAVED BY MACHINES", "RECYCLE ITEMS", "HAVE LIMITED ENERGY", "GAMBLE A LOT OF MONEY", "GAMBLE WITH YOUR LIFE", "TAKE CHANCES", "GO TO HEAVEN", "ARE ALREADY DEAD", "CHALLENGE GOD", "BELONG TO A GROUP OF REBELS", "ASSEMBLE A FORMIDABLE TEAM", "ACCEPT YOUR FATE", "ARE COLORBLIND", "COMMUNICATE TELEPATHICALLY", "HAVE A MENTAL BREAKDOWN", "ARE AT YOUR WITS END", "CAN MEMORIZE EVERY DETAIL", "LEAD A SECOND LIFE", "ARE HAUNTED BY A DEAD RELATIVE", "HAVE BEEN GIVEN SUPERPOWERS", "CAN TURN INTO A WEREWOLF", "ARE ABLE TO MANIPULATE SPACE AND TIME", "HAVE THE ABILITY TO SHAPESHIFT", "HEAR VOICES IN YOUR HEAD", "ARE A MASTER PICKPOCKET", "LEARN ABOUT YOUR PAST", "WAKE UP WITH NO MEMORIES", "READ THE MINDS OF OTHERS", "CAN TALK TO ANIMALS", "RELIVE YOUR WORST NIGHTMARES", "QUESTION REALITY", "SERVE JUSTICE", "ARE A FUGITIVE", "SMOKE CIGARETTES", "ARE THE LAST SURVIVING WIZARD", "HAVE PSYCHIC POWERS", "ARE A CHILD PRODIGY", "ARE BORN INTO A WEALTHY FAMILY", "ASSUME A SECRET IDENTITY", "ARE A TRAITOR", "STRIVE FOR PERFECTION", "HAVE PERFECT PITCH", "CAN HYPNOTIZE YOUR ENEMIES", "ARE A RETIRED JAZZ MUSICIAN", "CAN PHASE THROUGH WALLS"];

var thing = ["INFLUENCE YOUR PEERS", "DEFEAT A LEGION OF GHOULS", "RISE AGAINST THE OPPOSING FACTION", "TAKE CONTROL OF A WEAPONIZED MECH-SUIT", "FIGHT THROUGH HORDES OF ENEMIES", "GATHER AS MANY MATERIALS AS POSSIBLE", "COMPLETE EVERY QUEST", "DEAL WITH RANDOM ENCOUNTERS", "REPLACE STOLEN ARTIFACTS", "REPORT BACK TO HEADQUARTERS", "RAISE AN ARMY OF DINOSAURS", "RAISE AN ARMY OF SKELETONS", "RAISE AN ARMY OF SKELETONS", "PROGRESS DEEPER INTO A CAVE", "PROGRESS FURTHER INTO A DUNGEON", "FIND A LOST CITY", "RECOVER ANCIENT RELICS", "ASSIST A LESSER SPECIES", "TINKER WITH ALIEN WEAPONRY", "CONSTRUCT AN INTERPLANETARY VESSEL", "INVESTIGATE AN UNDERGROUND MILITARY BASE", "MAKE TRADES WITH TRAVELLING MERCHANTS", "SABOTAGE YOUR OWN TEAM", "TRANSPORT ILLICIT SUBSTANCES", "DRILL TO THE CORE OF THE PLANET", "ADVANCE IN YOUR CAREER", "LEARN HOW TO PLAY A MULTITUDE OF INSTRUMENTS", "SURMOUNT YOUR FEARS", "BEFRIEND AN ANCIENT DRAGON", "PRESENT TO A GALACTIC COUNCIL", "CRAFT GOD-SLAYING WEAPONS", "ESCAPE FROM PURGATORY", "SACRIFICE YOUR OWN LIFE", "GIVE UP EVERYTHING YOU HAVE", "SOLVE INCREASINGLY COMPLEX PUZZLES", "DECIPHER A SET OF ARCHAIC TEXTS", "COLLECT A SERIES OF MAGIC OBJECTS", "KIDNAP THE KING", "TRAVEL FROM PLANET TO PLANET", "CONSUME YOUR OWN BODY", "ASCEND TO THE HEAVENS", "DEVELOP A ROMANTIC RELATIONSHIP", "SLAY A GOD-LIKE ENTITY", "CREATE A PURIFICATION SERUM", "DEVELOP A CUTTING-EDGE SOURCE OF ENERGY"];

var achieve = ["SAVE THE PRINCESS", "SAVE A GIRL", "SAVE A BOY", "SAVE THE CHOSEN ONE", "SAVE THE WORLD", "TAKE OVER THE WORLD", "CONVINCE THE BAD GUY YOU'RE NOT A GOOD GUY", "OVERCOME THE EVIL THAT PLAGUES THE WORLD", "ACQUIRE AS MUCH LOOT AS YOU CAN", "MAKE THE MOST OF YOUR TIME LEFT ON EARTH", "OPEN PANDORA'S BOX", "IMPROVE EVERYBODY'S QUALITY OF LIFE", "EXPLORE EVERY INCH OF THE UNIVERSE", "BRING YOUR IMAGINATION TO LIFE", "REVERSE THE EVIL CURSE", "STOP EVERYONE FROM DREAMING", "SURVIVE FOR THE ENTIRE JOURNEY", "FALL IN LOVE", "BECOME RULER OF THE KINDGOM", "MAKE LOTS OF MONEY", "UNCOVER A WELL-KEPT SECRET", "PRETEND LIKE NOTHING EVER HAPPENED", "FIND SOMEWHERE SAFE FOR THE TIME-BEING", "KEEP THE MONSTERS AWAY", "HONE YOUR SKILLS", "JOIN THE BAD GUYS", "REGAIN YOUR LOST POWERS", "AVOID IMPENDING DOOM", "SUSTAIN THE ECOSYSTEM", "DESTROY THE WORLD", "FIND A CURE FOR THE VIRUS", "RETURN TO YOUR TIMELINE", "ABSORB THE POWERS OF FALLEN HEROES", "BRING DOWN THE GOVERNMENT", "PREVENT 'THE CORPORATION' FROM TAKING OVER", "RESOLVE A CRITICAL HOSTAGE SITUATION", "UNRAVEL A GLOBAL CONSPIRACY", "BECOME A MASTER BEEKEEPER", "ENSURE THE CITY IS FREE OF CRIME", "SACRIFICE YOURSELF FOR THE GREATER GOOD", "GAIN CONTROL OVER A REBEL MILITIA", "DESTROY THE SUN", "PREVENT THE UNIVERSE FROM COLLAPSING", "CLOSE A FISSURE IN SPACE AND TIME", "TRICK YOUR ENEMY INTO CONCEDING", "PROVIDE FOR YOUR FAMILY", "ESCAPE FROM THE SIMULATION" ];


function roll() {
	
	var setNum = Math.floor(Math.random() * (setting.length));
	var genNum = Math.floor(Math.random() * (genre.length));
	var verNum = Math.floor(Math.random() * (verb.length));
	var thiNum = Math.floor(Math.random() * (thing.length));
	var achNum = Math.floor(Math.random() * (achieve.length));
	
	var colNum = Math.floor(Math.random() * (11));
	
	if (colNum == 0) {
		document.getElementById("r_cont").style.backgroundColor = "#087da7";
		document.getElementById("btn").style.backgroundColor = "#087da7";
	} else if (colNum == 1) {
		document.getElementById("r_cont").style.backgroundColor = "#075d81";
		document.getElementById("btn").style.backgroundColor = "#075d81";
	} else if (colNum == 2) {
		document.getElementById("r_cont").style.backgroundColor = "#06415d";
		document.getElementById("btn").style.backgroundColor = "#06415d";
	} else if (colNum == 3) {
		document.getElementById("r_cont").style.backgroundColor = "#05253b";
		document.getElementById("btn").style.backgroundColor = "#05253b";
	} else if (colNum == 4) {
		document.getElementById("r_cont").style.backgroundColor = "#af1a0e";
		document.getElementById("btn").style.backgroundColor = "#af1a0e";
	} else if (colNum == 5) {
		document.getElementById("r_cont").style.backgroundColor = "#ce350f";
		document.getElementById("btn").style.backgroundColor = "#ce350f";
	} else if (colNum == 6) {
		document.getElementById("r_cont").style.backgroundColor = "#ed5110";
		document.getElementById("btn").style.backgroundColor = "#ed5110";
	} else if (colNum == 7) {
		document.getElementById("r_cont").style.backgroundColor = "#ea7218";
		document.getElementById("btn").style.backgroundColor = "#ea7218";
	} else if (colNum == 8) {
		document.getElementById("r_cont").style.backgroundColor = "#e69522";
		document.getElementById("btn").style.backgroundColor = "#e69522";
	} else if (colNum == 9) {
		document.getElementById("r_cont").style.backgroundColor = "#e5b82c";
		document.getElementById("btn").style.backgroundColor = "#e5b82c";
	} else if (colNum == 10) {
		document.getElementById("r_cont").style.backgroundColor = "#8ba551";
		document.getElementById("btn").style.backgroundColor = "#8ba551";
	}  else if (colNum == 11) {
		document.getElementById("r_cont").style.backgroundColor = "#41917a";
		document.getElementById("btn").style.backgroundColor = "#41917a";
	}
	
	document.getElementById('settingimg').src = "images/set/" + setNum + ".png"
	document.getElementById('genreimg').src = "images/gen/" + genNum + ".png"
	
	if (setNum < 7) {
		document.getElementById('r_idea').innerHTML = "AN " + setting[setNum] + " " + genre[genNum] + " WHERE YOU " + verb[verNum] + " AND MUST " + thing[thiNum] + " TO " + achieve[achNum]
	} else if (setNum > 6) {
		document.getElementById('r_idea').innerHTML = "A " + setting[setNum] + " " + genre[genNum] + " WHERE YOU  " + verb[verNum] + " AND MUST " + thing[thiNum] + " TO " + achieve[achNum];
	}
	
	document.getElementById('btn').innerHTML = "RE-ROLL"
	
	elm = document.getElementById('r_push');
	elm.classList.remove('pusher');
	void elm.offsetWidth;
	elm.classList.add('pusher');
}